/* ══════════════════════════════════════════════════════════════════════════════
   vigil-config.js — all static configuration, lookup tables, and icon data.
   No functions. Load this before vigil.js.
   ══════════════════════════════════════════════════════════════════════════════ */

/* ── Guardian API ────────────────────────────────────────────────────────────── */
var GUARDIAN_API = 'https://content.guardianapis.com/search?api-key=test&show-fields=trailText&page-size=5&order-by=newest&q=';

/* Guardian section slugs per Vigil category */
var GUARDIAN_SECTIONS = {
  Sports:     'sport',
  'Film & TV': 'film',
  Gaming:     'games',
  Technology: 'technology',
  Books:      'books',
  Podcasts:   'music',
  Design:     'artanddesign',
  Watches:    'fashion',
};

/* Extra search terms appended per category to help disambiguate entity names */
var CAT_QUERY_HINTS = {
  Watches:  ' watch',
  Podcasts: ' podcast',
  Gaming:   ' game',
};

/* ── ESPN API ────────────────────────────────────────────────────────────────── */
var ESPN_BASE        = 'https://site.api.espn.com/apis/site/v2/sports/';
var ESPN_TTL         = 900000; // 15 min cache per league feed

var ESPN_LEAGUE_NAMES = {
  'football/nfl':          'NFL · American Football',
  'basketball/nba':        'NBA · Basketball',
  'baseball/mlb':          'MLB · Baseball',
  'hockey/nhl':            'NHL · Ice Hockey',
  'soccer/eng.1':          'Premier League · Soccer',
  'soccer/esp.1':          'La Liga · Soccer',
  'soccer/ger.1':          'Bundesliga · Soccer',
  'soccer/usa.1':          'MLS · Soccer',
  'soccer/uefa.champions': 'UEFA Champions League · Soccer'
};

var ESPN_LEAGUES = [
  'football/nfl',
  'basketball/nba',
  'baseball/mlb',
  'hockey/nhl',
  'soccer/eng.1',
  'soccer/esp.1',
  'soccer/ger.1',
  'soccer/usa.1',
  'soccer/uefa.champions'
];

/* ── Team → League mapping ───────────────────────────────────────────────────── *
   Pins a known team/entity to a specific ESPN league path.
   loadEspnForEntity uses this to search 1 league instead of all 9.
   Keys are lowercased entity names (full and common aliases).           */
var TEAM_LEAGUE_MAP = {

  /* NBA ── basketball/nba */
  'atlanta hawks':             'basketball/nba',
  'boston celtics':            'basketball/nba',
  'celtics':                   'basketball/nba',
  'brooklyn nets':             'basketball/nba',
  'nets':                      'basketball/nba',
  'charlotte hornets':         'basketball/nba',
  'hornets':                   'basketball/nba',
  'chicago bulls':             'basketball/nba',
  'bulls':                     'basketball/nba',
  'cleveland cavaliers':       'basketball/nba',
  'cavaliers':                 'basketball/nba',
  'cavs':                      'basketball/nba',
  'dallas mavericks':          'basketball/nba',
  'mavericks':                 'basketball/nba',
  'mavs':                      'basketball/nba',
  'denver nuggets':            'basketball/nba',
  'nuggets':                   'basketball/nba',
  'detroit pistons':           'basketball/nba',
  'pistons':                   'basketball/nba',
  'golden state warriors':     'basketball/nba',
  'golden state':              'basketball/nba',
  'warriors':                  'basketball/nba',
  'houston rockets':           'basketball/nba',
  'rockets':                   'basketball/nba',
  'indiana pacers':            'basketball/nba',
  'pacers':                    'basketball/nba',
  'los angeles clippers':      'basketball/nba',
  'la clippers':               'basketball/nba',
  'clippers':                  'basketball/nba',
  'los angeles lakers':        'basketball/nba',
  'la lakers':                 'basketball/nba',
  'lakers':                    'basketball/nba',
  'memphis grizzlies':         'basketball/nba',
  'grizzlies':                 'basketball/nba',
  'miami heat':                'basketball/nba',
  'milwaukee bucks':           'basketball/nba',
  'bucks':                     'basketball/nba',
  'minnesota timberwolves':    'basketball/nba',
  'timberwolves':              'basketball/nba',
  'new orleans pelicans':      'basketball/nba',
  'pelicans':                  'basketball/nba',
  'new york knicks':           'basketball/nba',
  'knicks':                    'basketball/nba',
  'oklahoma city thunder':     'basketball/nba',
  'okc thunder':               'basketball/nba',
  'okc':                       'basketball/nba',
  'orlando magic':             'basketball/nba',
  'magic':                     'basketball/nba',
  'philadelphia 76ers':        'basketball/nba',
  '76ers':                     'basketball/nba',
  'sixers':                    'basketball/nba',
  'phoenix suns':              'basketball/nba',
  'suns':                      'basketball/nba',
  'portland trail blazers':    'basketball/nba',
  'trail blazers':             'basketball/nba',
  'blazers':                   'basketball/nba',
  'sacramento kings':          'basketball/nba',
  'kings':                     'basketball/nba',
  'san antonio spurs':         'basketball/nba',
  'toronto raptors':           'basketball/nba',
  'raptors':                   'basketball/nba',
  'utah jazz':                 'basketball/nba',
  'jazz':                      'basketball/nba',
  'washington wizards':        'basketball/nba',
  'wizards':                   'basketball/nba',

  /* NFL ── football/nfl */
  'arizona cardinals':         'football/nfl',
  'atlanta falcons':           'football/nfl',
  'falcons':                   'football/nfl',
  'baltimore ravens':          'football/nfl',
  'ravens':                    'football/nfl',
  'buffalo bills':             'football/nfl',
  'bills':                     'football/nfl',
  'carolina panthers':         'football/nfl',
  'panthers':                  'football/nfl',
  'chicago bears':             'football/nfl',
  'bears':                     'football/nfl',
  'cincinnati bengals':        'football/nfl',
  'bengals':                   'football/nfl',
  'cleveland browns':          'football/nfl',
  'browns':                    'football/nfl',
  'dallas cowboys':            'football/nfl',
  'cowboys':                   'football/nfl',
  'denver broncos':            'football/nfl',
  'broncos':                   'football/nfl',
  'detroit lions':             'football/nfl',
  'lions':                     'football/nfl',
  'green bay packers':         'football/nfl',
  'packers':                   'football/nfl',
  'houston texans':            'football/nfl',
  'texans':                    'football/nfl',
  'indianapolis colts':        'football/nfl',
  'colts':                     'football/nfl',
  'jacksonville jaguars':      'football/nfl',
  'jaguars':                   'football/nfl',
  'jags':                      'football/nfl',
  'kansas city chiefs':        'football/nfl',
  'chiefs':                    'football/nfl',
  'las vegas raiders':         'football/nfl',
  'raiders':                   'football/nfl',
  'los angeles chargers':      'football/nfl',
  'chargers':                  'football/nfl',
  'los angeles rams':          'football/nfl',
  'la rams':                   'football/nfl',
  'miami dolphins':            'football/nfl',
  'dolphins':                  'football/nfl',
  'minnesota vikings':         'football/nfl',
  'vikings':                   'football/nfl',
  'new england patriots':      'football/nfl',
  'patriots':                  'football/nfl',
  'pats':                      'football/nfl',
  'new orleans saints':        'football/nfl',
  'saints':                    'football/nfl',
  'new york giants':           'football/nfl',
  'giants':                    'football/nfl',
  'new york jets':             'football/nfl',
  'jets':                      'football/nfl',
  'philadelphia eagles':       'football/nfl',
  'pittsburgh steelers':       'football/nfl',
  'steelers':                  'football/nfl',
  'san francisco 49ers':       'football/nfl',
  '49ers':                     'football/nfl',
  'niners':                    'football/nfl',
  'seattle seahawks':          'football/nfl',
  'seahawks':                  'football/nfl',
  'tampa bay buccaneers':      'football/nfl',
  'buccaneers':                'football/nfl',
  'bucs':                      'football/nfl',
  'tennessee titans':          'football/nfl',
  'titans':                    'football/nfl',
  'washington commanders':     'football/nfl',
  'commanders':                'football/nfl',

  /* MLB ── baseball/mlb */
  'arizona diamondbacks':      'baseball/mlb',
  'diamondbacks':              'baseball/mlb',
  'd-backs':                   'baseball/mlb',
  'atlanta braves':            'baseball/mlb',
  'braves':                    'baseball/mlb',
  'baltimore orioles':         'baseball/mlb',
  'orioles':                   'baseball/mlb',
  'boston red sox':            'baseball/mlb',
  'red sox':                   'baseball/mlb',
  'chicago cubs':              'baseball/mlb',
  'cubs':                      'baseball/mlb',
  'chicago white sox':         'baseball/mlb',
  'white sox':                 'baseball/mlb',
  'cincinnati reds':           'baseball/mlb',
  'reds':                      'baseball/mlb',
  'cleveland guardians':       'baseball/mlb',
  'guardians':                 'baseball/mlb',
  'colorado rockies':          'baseball/mlb',
  'rockies':                   'baseball/mlb',
  'detroit tigers':            'baseball/mlb',
  'tigers':                    'baseball/mlb',
  'houston astros':            'baseball/mlb',
  'astros':                    'baseball/mlb',
  'kansas city royals':        'baseball/mlb',
  'royals':                    'baseball/mlb',
  'los angeles angels':        'baseball/mlb',
  'angels':                    'baseball/mlb',
  'los angeles dodgers':       'baseball/mlb',
  'dodgers':                   'baseball/mlb',
  'miami marlins':             'baseball/mlb',
  'marlins':                   'baseball/mlb',
  'milwaukee brewers':         'baseball/mlb',
  'brewers':                   'baseball/mlb',
  'minnesota twins':           'baseball/mlb',
  'twins':                     'baseball/mlb',
  'new york mets':             'baseball/mlb',
  'mets':                      'baseball/mlb',
  'new york yankees':          'baseball/mlb',
  'yankees':                   'baseball/mlb',
  'oakland athletics':         'baseball/mlb',
  'athletics':                 'baseball/mlb',
  "oakland a's":               'baseball/mlb',
  'philadelphia phillies':     'baseball/mlb',
  'phillies':                  'baseball/mlb',
  'pittsburgh pirates':        'baseball/mlb',
  'pirates':                   'baseball/mlb',
  'san diego padres':          'baseball/mlb',
  'padres':                    'baseball/mlb',
  'san francisco giants':      'baseball/mlb',
  'sf giants':                 'baseball/mlb',
  'seattle mariners':          'baseball/mlb',
  'mariners':                  'baseball/mlb',
  'st. louis cardinals':       'baseball/mlb',
  'cardinals':                 'baseball/mlb',
  'tampa bay rays':            'baseball/mlb',
  'rays':                      'baseball/mlb',
  'texas rangers':             'baseball/mlb',
  'toronto blue jays':         'baseball/mlb',
  'blue jays':                 'baseball/mlb',
  'washington nationals':      'baseball/mlb',
  'nationals':                 'baseball/mlb',

  /* NHL ── hockey/nhl */
  'anaheim ducks':             'hockey/nhl',
  'ducks':                     'hockey/nhl',
  'boston bruins':             'hockey/nhl',
  'bruins':                    'hockey/nhl',
  'buffalo sabres':            'hockey/nhl',
  'sabres':                    'hockey/nhl',
  'calgary flames':            'hockey/nhl',
  'flames':                    'hockey/nhl',
  'carolina hurricanes':       'hockey/nhl',
  'hurricanes':                'hockey/nhl',
  'chicago blackhawks':        'hockey/nhl',
  'blackhawks':                'hockey/nhl',
  'colorado avalanche':        'hockey/nhl',
  'avalanche':                 'hockey/nhl',
  'avs':                       'hockey/nhl',
  'columbus blue jackets':     'hockey/nhl',
  'blue jackets':              'hockey/nhl',
  'dallas stars':              'hockey/nhl',
  'stars':                     'hockey/nhl',
  'edmonton oilers':           'hockey/nhl',
  'oilers':                    'hockey/nhl',
  'florida panthers':          'hockey/nhl',
  'las vegas golden knights':  'hockey/nhl',
  'golden knights':            'hockey/nhl',
  'los angeles kings':         'hockey/nhl',
  'la kings':                  'hockey/nhl',
  'minnesota wild':            'hockey/nhl',
  'wild':                      'hockey/nhl',
  'montreal canadiens':        'hockey/nhl',
  'canadiens':                 'hockey/nhl',
  'habs':                      'hockey/nhl',
  'nashville predators':       'hockey/nhl',
  'predators':                 'hockey/nhl',
  'preds':                     'hockey/nhl',
  'new jersey devils':         'hockey/nhl',
  'devils':                    'hockey/nhl',
  'new york islanders':        'hockey/nhl',
  'islanders':                 'hockey/nhl',
  'new york rangers':          'hockey/nhl',
  'ny rangers':                'hockey/nhl',
  'ottawa senators':           'hockey/nhl',
  'senators':                  'hockey/nhl',
  'philadelphia flyers':       'hockey/nhl',
  'flyers':                    'hockey/nhl',
  'pittsburgh penguins':       'hockey/nhl',
  'penguins':                  'hockey/nhl',
  'pens':                      'hockey/nhl',
  'san jose sharks':           'hockey/nhl',
  'sharks':                    'hockey/nhl',
  'seattle kraken':            'hockey/nhl',
  'kraken':                    'hockey/nhl',
  'st. louis blues':           'hockey/nhl',
  'blues':                     'hockey/nhl',
  'tampa bay lightning':       'hockey/nhl',
  'lightning':                 'hockey/nhl',
  'toronto maple leafs':       'hockey/nhl',
  'maple leafs':               'hockey/nhl',
  'leafs':                     'hockey/nhl',
  'utah hockey club':          'hockey/nhl',
  'vancouver canucks':         'hockey/nhl',
  'canucks':                   'hockey/nhl',
  'vegas golden knights':      'hockey/nhl',
  'washington capitals':       'hockey/nhl',
  'capitals':                  'hockey/nhl',
  'caps':                      'hockey/nhl',
  'winnipeg jets':             'hockey/nhl',

  /* EPL ── soccer/eng.1 */
  'arsenal':                   'soccer/eng.1',
  'aston villa':               'soccer/eng.1',
  'bournemouth':               'soccer/eng.1',
  'brentford':                 'soccer/eng.1',
  'brighton':                  'soccer/eng.1',
  'brighton & hove albion':    'soccer/eng.1',
  'chelsea':                   'soccer/eng.1',
  'crystal palace':            'soccer/eng.1',
  'everton':                   'soccer/eng.1',
  'fulham':                    'soccer/eng.1',
  'ipswich town':              'soccer/eng.1',
  'ipswich':                   'soccer/eng.1',
  'leicester city':            'soccer/eng.1',
  'leicester':                 'soccer/eng.1',
  'liverpool':                 'soccer/eng.1',
  'man city':                  'soccer/eng.1',
  'man utd':                   'soccer/eng.1',
  'manchester city':           'soccer/eng.1',
  'manchester united':         'soccer/eng.1',
  'manchester united fc':      'soccer/eng.1',
  'newcastle':                 'soccer/eng.1',
  'newcastle united':          'soccer/eng.1',
  'nottingham forest':         'soccer/eng.1',
  'southampton':               'soccer/eng.1',
  'tottenham':                 'soccer/eng.1',
  'tottenham hotspur':         'soccer/eng.1',
  'spurs':                     'soccer/eng.1',
  'west ham':                  'soccer/eng.1',
  'west ham united':           'soccer/eng.1',
  'wolves':                    'soccer/eng.1',
  'wolverhampton':             'soccer/eng.1',
  'wolverhampton wanderers':   'soccer/eng.1',

  /* La Liga ── soccer/esp.1 */
  'atletico madrid':           'soccer/esp.1',
  'atlético madrid':           'soccer/esp.1',
  'atletico':                  'soccer/esp.1',
  'athletic bilbao':           'soccer/esp.1',
  'barcelona':                 'soccer/esp.1',
  'fc barcelona':              'soccer/esp.1',
  'celta vigo':                'soccer/esp.1',
  'getafe':                    'soccer/esp.1',
  'girona':                    'soccer/esp.1',
  'osasuna':                   'soccer/esp.1',
  'rayo vallecano':            'soccer/esp.1',
  'real betis':                'soccer/esp.1',
  'real madrid':               'soccer/esp.1',
  'real sociedad':             'soccer/esp.1',
  'real valladolid':           'soccer/esp.1',
  'sevilla':                   'soccer/esp.1',
  'valencia':                  'soccer/esp.1',
  'villarreal':                'soccer/esp.1',

  /* Bundesliga ── soccer/ger.1 */
  'augsburg':                  'soccer/ger.1',
  'bayer leverkusen':          'soccer/ger.1',
  'leverkusen':                'soccer/ger.1',
  'bayern munich':             'soccer/ger.1',
  'fc bayern':                 'soccer/ger.1',
  'bayern':                    'soccer/ger.1',
  'borussia dortmund':         'soccer/ger.1',
  'dortmund':                  'soccer/ger.1',
  'bvb':                       'soccer/ger.1',
  'borussia mönchengladbach':  'soccer/ger.1',
  'gladbach':                  'soccer/ger.1',
  'eintracht frankfurt':       'soccer/ger.1',
  'frankfurt':                 'soccer/ger.1',
  'freiburg':                  'soccer/ger.1',
  'hamburger sv':              'soccer/ger.1',
  'hamburg':                   'soccer/ger.1',
  'hoffenheim':                'soccer/ger.1',
  'rb leipzig':                'soccer/ger.1',
  'leipzig':                   'soccer/ger.1',
  'mainz':                     'soccer/ger.1',
  'schalke':                   'soccer/ger.1',
  'stuttgart':                 'soccer/ger.1',
  'vfb stuttgart':             'soccer/ger.1',
  'union berlin':              'soccer/ger.1',
  'werder bremen':             'soccer/ger.1',
  'bremen':                    'soccer/ger.1',
  'wolfsburg':                 'soccer/ger.1',

  /* MLS ── soccer/usa.1 */
  'atlanta united':            'soccer/usa.1',
  'austin fc':                 'soccer/usa.1',
  'charlotte fc':              'soccer/usa.1',
  'chicago fire':              'soccer/usa.1',
  'fc cincinnati':             'soccer/usa.1',
  'cincinnati':                'soccer/usa.1',
  'colorado rapids':           'soccer/usa.1',
  'rapids':                    'soccer/usa.1',
  'columbus crew':             'soccer/usa.1',
  'd.c. united':               'soccer/usa.1',
  'dc united':                 'soccer/usa.1',
  'fc dallas':                 'soccer/usa.1',
  'houston dynamo':            'soccer/usa.1',
  'dynamo':                    'soccer/usa.1',
  'inter miami':               'soccer/usa.1',
  'la galaxy':                 'soccer/usa.1',
  'galaxy':                    'soccer/usa.1',
  'lafc':                      'soccer/usa.1',
  'los angeles fc':            'soccer/usa.1',
  'minnesota united':          'soccer/usa.1',
  'cf montréal':               'soccer/usa.1',
  'montreal':                  'soccer/usa.1',
  'nashville sc':              'soccer/usa.1',
  'nashville':                 'soccer/usa.1',
  'new england revolution':    'soccer/usa.1',
  'revolution':                'soccer/usa.1',
  'new york city fc':          'soccer/usa.1',
  'nycfc':                     'soccer/usa.1',
  'new york red bulls':        'soccer/usa.1',
  'red bulls':                 'soccer/usa.1',
  'orlando city':              'soccer/usa.1',
  'philadelphia union':        'soccer/usa.1',
  'union':                     'soccer/usa.1',
  'portland timbers':          'soccer/usa.1',
  'timbers':                   'soccer/usa.1',
  'real salt lake':            'soccer/usa.1',
  'rsl':                       'soccer/usa.1',
  'san jose earthquakes':      'soccer/usa.1',
  'earthquakes':               'soccer/usa.1',
  'seattle sounders':          'soccer/usa.1',
  'sounders':                  'soccer/usa.1',
  'sporting kansas city':      'soccer/usa.1',
  'skc':                       'soccer/usa.1',
  'st. louis city':            'soccer/usa.1',
  'toronto fc':                'soccer/usa.1',
  'tfc':                       'soccer/usa.1',
  'vancouver whitecaps':       'soccer/usa.1',
  'whitecaps':                 'soccer/usa.1',
};

/* ── ESPN entity match terms ─────────────────────────────────────────────────── *
   Key: lowercased entity name the user might type.
   Value: array of strings ALL of which must appear in an ESPN article headline
   (or 2+ times in the combined headline+description) for a match.
   Single-word values are used for teams whose nickname alone is unambiguous.   */
var ESPN_ENTITY_ALIASES = {
  // Premier League clubs
  'man utd':                ['manchester', 'united'],
  'manchester united':      ['manchester', 'united'],
  'manchester united fc':   ['manchester', 'united'],
  'man city':               ['manchester', 'city'],
  'manchester city':        ['manchester', 'city'],
  'tottenham':              ['tottenham'],
  'spurs':                  ['tottenham'],
  'arsenal':                ['arsenal'],
  'chelsea':                ['chelsea'],
  'liverpool':              ['liverpool'],
  'newcastle':              ['newcastle'],
  'newcastle united':       ['newcastle'],
  'aston villa':            ['aston', 'villa'],
  'west ham':               ['west', 'ham'],
  'west ham united':        ['west', 'ham'],
  'brighton':               ['brighton'],
  'everton':                ['everton'],
  'brentford':              ['brentford'],
  'fulham':                 ['fulham'],
  'wolves':                 ['wolverhampton'],
  'wolverhampton':          ['wolverhampton'],
  'wolverhampton wanderers':['wolverhampton'],
  'nottingham forest':      ['nottingham'],
  'crystal palace':         ['palace'],
  'leicester':              ['leicester'],
  'leicester city':         ['leicester'],
  'bournemouth':            ['bournemouth'],
  'southampton':            ['southampton'],
  'ipswich':                ['ipswich'],
  'ipswich town':           ['ipswich'],

  // La Liga
  'real madrid':            ['real', 'madrid'],
  'barcelona':              ['barcelona'],
  'fc barcelona':           ['barcelona'],
  'atletico madrid':        ['atlético', 'madrid'],
  'atlético madrid':        ['atlético', 'madrid'],
  'atletico':               ['atlético'],
  'sevilla':                ['sevilla'],
  'real sociedad':          ['real', 'sociedad'],
  'villarreal':             ['villarreal'],
  'athletic bilbao':        ['athletic', 'bilbao'],
  'real betis':             ['betis'],
  'valencia':               ['valencia'],
  'girona':                 ['girona'],

  // Bundesliga
  'bayern munich':          ['bayern'],
  'fc bayern':              ['bayern'],
  'bayern':                 ['bayern'],
  'borussia dortmund':      ['dortmund'],
  'dortmund':               ['dortmund'],
  'bvb':                    ['dortmund'],
  'rb leipzig':             ['leipzig'],
  'leipzig':                ['leipzig'],
  'bayer leverkusen':       ['leverkusen'],
  'leverkusen':             ['leverkusen'],
  'eintracht frankfurt':    ['frankfurt'],
  'borussia mönchengladbach':['gladbach'],
  'gladbach':               ['gladbach'],
  'wolfsburg':              ['wolfsburg'],
  'freiburg':               ['freiburg'],
  'stuttgart':              ['stuttgart'],
  'union berlin':           ['union', 'berlin'],
  'werder bremen':          ['werder'],
  'hoffenheim':             ['hoffenheim'],
  'mainz':                  ['mainz'],
  'augsburg':               ['augsburg'],

  // MLS
  'la galaxy':              ['galaxy'],
  'inter miami':            ['inter', 'miami'],
  'nycfc':                  ['new york city'],
  'new york city fc':       ['new york city'],
  'red bulls':              ['york', 'bulls'],
  'new york red bulls':     ['york', 'bulls'],
  'seattle sounders':       ['sounders'],
  'portland timbers':       ['timbers'],
  'atlanta united':         ['atlanta', 'united'],
  'lafc':                   ['angeles', 'lafc'],
  'sporting kansas city':   ['sporting', 'kansas'],
  'nashville sc':           ['nashville'],

  // NBA — ESPN headlines use nickname only
  'oklahoma city thunder':  ['thunder'],
  'okc thunder':            ['thunder'],
  'okc':                    ['thunder'],
  'golden state warriors':  ['warriors'],
  'golden state':           ['warriors'],
  'los angeles lakers':     ['lakers'],
  'la lakers':              ['lakers'],
  'lakers':                 ['lakers'],
  'los angeles clippers':   ['clippers'],
  'clippers':               ['clippers'],
  'new york knicks':        ['knicks'],
  'knicks':                 ['knicks'],
  'boston celtics':         ['celtics'],
  'celtics':                ['celtics'],
  'miami heat':             ['miami', 'heat'],   // 'heat' alone too noisy
  'chicago bulls':          ['bulls'],
  'bulls':                  ['bulls'],
  'milwaukee bucks':        ['bucks'],
  'bucks':                  ['bucks'],
  'phoenix suns':           ['suns'],
  'denver nuggets':         ['nuggets'],
  'nuggets':                ['nuggets'],
  'minnesota timberwolves': ['timberwolves'],
  'timberwolves':           ['timberwolves'],
  'dallas mavericks':       ['mavericks'],
  'mavericks':              ['mavericks'],
  'mavs':                   ['mavericks'],
  'san antonio spurs':      ['spurs', 'antonio'],  // 'spurs' clashes with Tottenham
  'memphis grizzlies':      ['grizzlies'],
  'grizzlies':              ['grizzlies'],
  'indiana pacers':         ['pacers'],
  'pacers':                 ['pacers'],
  'toronto raptors':        ['raptors'],
  'raptors':                ['raptors'],
  'new orleans pelicans':   ['pelicans'],
  'pelicans':               ['pelicans'],
  'portland trail blazers': ['blazers'],
  'trail blazers':          ['blazers'],
  'blazers':                ['blazers'],
  'sacramento kings':       ['sacramento', 'kings'],  // 'kings' clashes with hockey
  'washington wizards':     ['wizards'],
  'wizards':                ['wizards'],
  'charlotte hornets':      ['hornets'],
  'hornets':                ['hornets'],
  'atlanta hawks':          ['hawks'],
  'hawks':                  ['hawks'],
  'detroit pistons':        ['pistons'],
  'pistons':                ['pistons'],
  'cleveland cavaliers':    ['cavaliers'],
  'cavaliers':              ['cavaliers'],
  'cavs':                   ['cavaliers'],
  'houston rockets':        ['rockets'],
  'rockets':                ['rockets'],
  'brooklyn nets':          ['nets'],
  'nets':                   ['nets'],
  'orlando magic':          ['magic'],
  'philadelphia 76ers':     ['76ers'],
  '76ers':                  ['76ers'],
  'sixers':                 ['76ers'],
  'utah jazz':              ['jazz'],
  'jazz':                   ['jazz'],

  // NFL
  'kansas city chiefs':     ['chiefs'],
  'chiefs':                 ['chiefs'],
  'san francisco 49ers':    ['49ers'],
  '49ers':                  ['49ers'],
  'niners':                 ['49ers'],
  'green bay packers':      ['packers'],
  'packers':                ['packers'],
  'new england patriots':   ['patriots'],
  'patriots':               ['patriots'],
  'dallas cowboys':         ['cowboys'],
  'cowboys':                ['cowboys'],
  'buffalo bills':          ['bills'],
  'bills':                  ['bills'],
  'philadelphia eagles':    ['eagles'],
  'eagles':                 ['eagles'],
  'baltimore ravens':       ['ravens'],
  'ravens':                 ['ravens'],
  'pittsburgh steelers':    ['steelers'],
  'steelers':               ['steelers'],
  'denver broncos':         ['broncos'],
  'broncos':                ['broncos'],
  'seattle seahawks':       ['seahawks'],
  'seahawks':               ['seahawks'],
  'minnesota vikings':      ['vikings'],
  'vikings':                ['vikings'],
  'los angeles rams':       ['rams'],
  'la rams':                ['rams'],
  'tampa bay buccaneers':   ['buccaneers'],
  'buccaneers':             ['buccaneers'],
  'bucs':                   ['buccaneers'],
  'las vegas raiders':      ['raiders'],
  'raiders':                ['raiders'],
  'miami dolphins':         ['dolphins'],
  'dolphins':               ['dolphins'],
  'indianapolis colts':     ['colts'],
  'colts':                  ['colts'],
  'cincinnati bengals':     ['bengals'],
  'bengals':                ['bengals'],
  'jacksonville jaguars':   ['jaguars'],
  'jaguars':                ['jaguars'],
  'jags':                   ['jaguars'],
  'new york giants':        ['giants'],
  'giants':                 ['giants'],
  'new york jets':          ['jets'],
  'jets':                   ['jets'],
  'carolina panthers':      ['panthers'],
  'panthers':               ['panthers'],
  'tennessee titans':       ['titans'],
  'titans':                 ['titans'],
  'houston texans':         ['texans'],
  'texans':                 ['texans'],
  'detroit lions':          ['lions'],
  'lions':                  ['lions'],
  'chicago bears':          ['bears'],
  'bears':                  ['bears'],
  'new orleans saints':     ['saints'],
  'saints':                 ['saints'],
  'los angeles chargers':   ['chargers'],
  'chargers':               ['chargers'],
  'arizona cardinals':      ['cardinals'],
  'atlanta falcons':        ['falcons'],
  'falcons':                ['falcons'],
  'washington commanders':  ['commanders'],
  'commanders':             ['commanders'],
  'cleveland browns':       ['browns'],
  'browns':                 ['browns'],

  // NHL
  'toronto maple leafs':    ['maple', 'leafs'],
  'maple leafs':            ['maple', 'leafs'],
  'leafs':                  ['maple', 'leafs'],
  'montreal canadiens':     ['canadiens'],
  'canadiens':              ['canadiens'],
  'habs':                   ['canadiens'],
  'boston bruins':          ['bruins'],
  'bruins':                 ['bruins'],
  'chicago blackhawks':     ['blackhawks'],
  'blackhawks':             ['blackhawks'],
  'pittsburgh penguins':    ['penguins'],
  'penguins':               ['penguins'],
  'new york rangers':       ['rangers', 'york'],  // 'rangers' clashes with Texas Rangers
  'ny rangers':             ['rangers', 'york'],
  'edmonton oilers':        ['oilers'],
  'oilers':                 ['oilers'],
  'colorado avalanche':     ['avalanche'],
  'avalanche':              ['avalanche'],
  'avs':                    ['avalanche'],
  'vegas golden knights':   ['golden', 'knights'],
  'las vegas golden knights':['golden', 'knights'],
  'golden knights':         ['golden', 'knights'],
  'tampa bay lightning':    ['lightning'],
  'lightning':              ['lightning'],
  'carolina hurricanes':    ['hurricanes'],
  'hurricanes':             ['hurricanes'],
  'florida panthers':       ['florida', 'panthers'],  // 'panthers' clashes with NFL Carolina
  'washington capitals':    ['capitals'],
  'capitals':               ['capitals'],
  'caps':                   ['capitals'],
  'dallas stars':           ['stars'],
  'stars':                  ['stars'],
  'nashville predators':    ['predators'],
  'predators':              ['predators'],
  'preds':                  ['predators'],
  'los angeles kings':      ['kings', 'angeles'],  // 'kings' clashes with basketball
  'la kings':               ['kings', 'angeles'],
  'philadelphia flyers':    ['flyers'],
  'flyers':                 ['flyers'],
  'minnessota wild':        ['wild'],
  'minnesota wild':         ['wild'],
  'wild':                   ['wild'],
  'new jersey devils':      ['devils'],
  'devils':                 ['devils'],
  'seattle kraken':         ['kraken'],
  'kraken':                 ['kraken'],
  'buffalo sabres':         ['sabres'],
  'sabres':                 ['sabres'],
  'st. louis blues':        ['blues'],
  'blues':                  ['blues'],
  'winnipeg jets':          ['jets', 'winnipeg'],  // 'jets' clashes with NFL NY Jets
  'vancouver canucks':      ['canucks'],
  'canucks':                ['canucks'],
  'calgary flames':         ['flames'],
  'flames':                 ['flames'],
  'ottawa senators':        ['senators'],
  'senators':               ['senators'],
  'new york islanders':     ['islanders'],
  'islanders':              ['islanders'],
  'anaheim ducks':          ['ducks'],
  'ducks':                  ['ducks'],
  'columbus blue jackets':  ['blue', 'jackets'],
  'blue jackets':           ['blue', 'jackets'],

  // International / UCL clubs
  'psg':                    ['paris', 'saint-germain'],
  'paris sg':               ['paris', 'saint-germain'],
  'paris saint-germain':    ['paris', 'saint-germain'],
  'ajax':                   ['ajax'],
  'celtic':                 ['celtic'],
  'rangers fc':             ['rangers', 'scotland'],  // avoids NHL/MLB Rangers
  'juventus':               ['juventus'],
  'inter milan':            ['inter', 'milan'],
  'inter':                  ['inter', 'milan'],
  'ac milan':               ['milan'],
  'roma':                   ['roma'],
  'lazio':                  ['lazio'],
  'napoli':                 ['napoli'],
  'porto':                  ['porto'],
  'benfica':                ['benfica'],
  'sporting cp':            ['sporting', 'portugal'],
};

/* ── Category colours ────────────────────────────────────────────────────────── */
var CAT_COLORS = {
  Music:         { c: '#c0404a', bg: 'rgba(192,64,74,0.12)'   },
  Sports:        { c: '#2e8a4a', bg: 'rgba(46,138,74,0.12)'   },
  'Film & TV':   { c: '#b86a2e', bg: 'rgba(184,106,46,0.12)'  },
  Film:          { c: '#b86a2e', bg: 'rgba(184,106,46,0.12)'  }, // legacy key
  Gaming:        { c: '#3a6aab', bg: 'rgba(58,106,171,0.12)'  },
  Technology:    { c: '#3a8c5c', bg: 'rgba(58,140,92,0.12)'   },
  Books:         { c: '#6a4aab', bg: 'rgba(106,74,171,0.12)'  },
  Podcasts:      { c: '#a06030', bg: 'rgba(160,96,48,0.12)'   },
  Watches:       { c: '#8a7a3a', bg: 'rgba(138,122,58,0.12)'  },
  Design:        { c: '#a04080', bg: 'rgba(160,64,128,0.12)'  },
  Accessibility: { c: '#2e7a8a', bg: 'rgba(46,122,138,0.12)'  },
  Development:   { c: '#3a6aab', bg: 'rgba(58,106,171,0.12)'  },
  Research:      { c: '#6a4aab', bg: 'rgba(106,74,171,0.12)'  },
  Tools:         { c: '#3a8c5c', bg: 'rgba(58,140,92,0.12)'   },
  Other:         { c: '#555570', bg: 'rgba(85,85,112,0.12)'   }
};

/* ── Category icons (emoji) ──────────────────────────────────────────────────── */
var CAT_ICONS = {
  Music:         '🎵',
  Sports:        '⚽',
  'Film & TV':   '🎬',
  Film:          '🎬',
  Gaming:        '🎮',
  Technology:    '💻',
  Books:         '📚',
  Podcasts:      '🎙',
  Watches:       '⌚',
  Design:        '✏️',
  Accessibility: '♿',
  Development:   '⌨️',
  Research:      '🔬',
  Tools:         '🔧',
  Other:         '📌'
};

/* ── Sport-specific line icons ───────────────────────────────────────────────── */
var SPORT_ICONS = {
  'Soccer':           '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><polygon points="12,7 15.4,9.5 14.1,13.5 9.9,13.5 8.6,9.5"/><line x1="12" y1="7" x2="12" y2="3"/><line x1="15.4" y1="9.5" x2="20.2" y2="7.6"/><line x1="14.1" y1="13.5" x2="17.9" y2="18.2"/><line x1="9.9" y1="13.5" x2="6.1" y2="18.2"/><line x1="8.6" y1="9.5" x2="3.8" y2="7.6"/></svg>',
  'Basketball':       '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><line x1="3" y1="12" x2="21" y2="12"/><path d="M12 3 Q18 7 18 12 Q18 17 12 21"/><path d="M12 3 Q6 7 6 12 Q6 17 12 21"/></svg>',
  'American Football':'<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12 Q12 3 20 12 Q12 21 4 12 Z"/><line x1="12" y1="6" x2="12" y2="18"/><line x1="9.5" y1="9.5" x2="14.5" y2="9.5"/><line x1="9.5" y1="12" x2="14.5" y2="12"/><line x1="9.5" y1="14.5" x2="14.5" y2="14.5"/></svg>',
  'Baseball':         '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M9.5 4.5 Q5.5 12 9.5 19.5"/><path d="M14.5 4.5 Q18.5 12 14.5 19.5"/></svg>',
  'Ice Hockey':       '<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="8" y1="3" x2="8" y2="16"/><path d="M8 16 Q8 20 12 20 L17 20"/><ellipse cx="20" cy="20" rx="2.5" ry="1.5"/></svg>',
};

/* ── UI SVG icons ────────────────────────────────────────────────────────────── */
var SVG = {
  eye:     '<svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>',
  close:   '<svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>',
  share:   '<svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></svg>',
  chevron: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="6 9 12 15 18 9"/></svg>'
};
